apiVersion: v1
kind: Namespace
metadata:
  name: simpletimeservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
  namespace: simpletimeservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
      - name: simpletimeservice
        image: sumit0058/simpletimeservice
        ports:
        - containerPort: 5000

        # Updates to the Kubernetes manifest to utilize best practices (e.g. pod CPU and memory limits)
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"

  # A sidecar container fluentbit to collect and forward logs from main application container
  #     - name: fluentbit
  #       image: fluent/fluent-bit:latest
  #       resources:
  #         requests:
  #           memory: "32Mi"
  #           cpu: "50m"
  #         limits:
  #           memory: "64Mi"
  #           cpu: "100m"

  #       volumeMounts:
  #       - name: logs
  #         mountPath: /fluent-bit/logs

  # volumes:
  # - name: logs
  #   emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice-service
  namespace: simpletimeservice
spec:
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
