apiVersion: v1
kind: Namespace
metadata:
  name: simpletimeservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
  namespace: simpletimeservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
      - name: simpletimeservice
        image: sumit0058/simpletimeservice
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice-service
  namespace: simpletimeservice
spec:
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort


# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-time-service-service
#   namespace: simple-time-service-namespace
# spec:
#   selector:
#     app: simple-time-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
